version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=webgames
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=webgames
  redis:
    image: redis:alpine
  nginx:
    build: ./nginx
    links:
      - webapi:webapi
    volumes:
      - ./nginx/www:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    ports:
      - 80:80
      - 443:443
    command: ["dockerize", "-template", "/etc/nginx/conf.d/redirect.conf.tmpl:/etc/nginx/conf.d/redirect.conf", "-template", "/etc/nginx/conf.d/webapi.conf.tmpl:/etc/nginx/conf.d/webapi.conf", "-wait", "http://webapi:5000/check", "nginx", "-g", "daemon off;"]
  webapi:
    build: ./api
    environment:
      - USE_SSL=false
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MANAGER_HOST=manager
      - JWT_SECRET=${JWT_SECRET}
    links:
      - postgres:postgres
      - redis:redis
    command: ["dockerize", "-wait", "tcp://postgres:5432", "-wait", "tcp://redis:6379", "yarn", "server:prod"]
  manager:
    build: ./manager
    environment:
      - API_URL=http://api.webgames.ephec-ti.be
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
    links:
      - redis:redis
      - nginx:nginx
      - nginx:api.webgames.ephec-ti.be
    ports:
      - 4170:4170
      - 4171:4171
    volumes:
      - ./manager:/usr/src/app
    command: ["dockerize", "-wait", "tcp://redis:6379", "-wait", "http://api.webgames.ephec-ti.be/check", "python", "start.py"]

