# WebGames settings, environ var prefix: WG_
webgames:
    host: localhost
    port: 50898
    domain: example.com
    schemessl: no

# Database settings, environ var prefix: PG
# See documentation at https://magicstack.github.io/asyncpg/current/api/index.html#connection
postgres:
    host: localhost
    port: null
    user: postgres
    password: super-secret-password
    database: webgames
    salt: super-secret-salt

# SMTP settings, environ var prefix: SMTP_
smtp:
    host: localhost
    port: 0
    ssl: no
    user: username
    password: super-secret-password

# redis settings, environ var prefix: REDIS_
# See documentation at index.html#asyncio_redis.Pool.create
redis:
    host: localhost
    port: 6379
    password: null
    db: 1
    siodb: 0
    poolsize: 10


# Logs settings, environ var prefix: WG_LOG_
# See documentation at https://docs.python.org/3.6/library/logging.html
log:
    # environ var prefix: WG_LOG_STDOUT
    stdout:
        enabled: yes
        level: INFO
        format: "[{levelname}] <{name}:{funcName}> {message}"
    # environ var prefix: WG_LOG_FILE
    file:
        enabled: yes
        level: DEBUG
        format: "{asctime} [{levelname}] <{name}:{funcName}> {message}"
        name: latest.log
        archive: no

# Tokens settings, environ var prefix: WG_TK
token:
    length: 16
    validity: 1d

# Tokens settings, environ var prefix: WG_CHLG
challenge:
    length: 24
    validity: 1d
