LOG_LEVEL: "DEBUG"

API_URL: "http://localhost:8080"

SERVER_HOST: "0.0.0.0"
SERVER_TCP_PORT: 4170
SERVER_WS_PORT: 4171

JWT_EXPIRATION_TIME: "12h"
JWT_SECRET: "superabricot2000"

PING_HEARTBEAT: "5m"
PING_TIMEOUT: "1s"

SSL: false
SSL_CERT_FILE: "/tmp/cert.pem"
SSL_KEY_FILE: "/tmp/key.pem"

REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: null
REDIS_DATABASE: 0
