LOG_LEVEL: "DEBUG"

API_URL: "http://localhost:8080"

MANAGER_HOST: "0.0.0.0"
MANAGER_TCP_PORT: 4170
MANAGER_WS_PORT: 4171
UDP_BROADCASTER_PORT: 4172

JWT_EXPIRATION_TIME: "12h"
JWT_SECRET: null
READY_CHECK_TIMEOUT: "10s"

PING_HEARTBEAT: "5m"
PING_TIMEOUT: "1s"

USE_SSL: false
SSL_CERT_FILE: "/tmp/cert.pem"
SSL_KEY_FILE: "/tmp/key.pem"

REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: null
REDIS_DB_MANAGER: 0
