LOG_LEVEL: "DEBUG"

WEBAPI_HOST: "0.0.0.0"
WEBAPI_PORT: 4173

JWT_EXPIRATION_TIME: "12h"
JWT_SECRET: null

TOKEN_EXPIRATION_TIME: "2h"

USE_SSL: false
SSL_CERT_FILE: "/tmp/cert.pem"
SSL_KEY_FILE: "/tmp/key.pem"

REDIS_HOST: localhost
REDIS_PORT: 6379
REDIS_PASSWORD: null
REDIS_DB: 0

POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_USER: webgames
POSTGRES_DB: webgames
POSTGRES_PASSWORD: null
